#!/bin/bash
#
# SSH Hardening Setup Script
# Configures secure SSH settings on Ubuntu/Debian systems
#
# WARNING: This script modifies SSH configuration. Use with caution!
# Always keep an active SSH session open when running this script.
#

set -e  # Exit on error

echo "========================================="
echo "  SSH Hardening Setup Script"
echo "========================================="
echo ""
echo "WARNING: This script will modify SSH configuration."
echo "Ensure you have:"
echo "  1. An active SSH session open (don't close it!)"
echo "  2. SSH keys already configured for your user"
echo "  3. Tested SSH key login in a separate session"
echo ""
read -p "Continue? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Aborted."
    exit 1
fi

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root or with sudo" 
   exit 1
fi

# Prompt for non-root username
read -p "Enter the username for SSH access (e.g., deployer): " SSH_USER

if [ -z "$SSH_USER" ]; then
    echo "Username cannot be empty"
    exit 1
fi

# Check if user exists
if ! id "$SSH_USER" &>/dev/null; then
    echo "User $SSH_USER does not exist."
    read -p "Create this user? (yes/no): " CREATE_USER
    
    if [ "$CREATE_USER" == "yes" ]; then
        adduser "$SSH_USER"
        usermod -aG sudo "$SSH_USER"
        echo "User $SSH_USER created and added to sudo group"
    else
        echo "Aborted. Please create the user first."
        exit 1
    fi
fi

# Backup original sshd_config
BACKUP_FILE="/etc/ssh/sshd_config.backup.$(date +%Y%m%d-%H%M%S)"
echo ""
echo "[1/3] Backing up current SSH configuration..."
cp /etc/ssh/sshd_config "$BACKUP_FILE"
echo "Backup saved to: $BACKUP_FILE"

# Create hardened SSH configuration
echo ""
echo "[2/3] Applying SSH hardening settings..."

cat > /etc/ssh/sshd_config.d/99-hardening.conf <<EOF
# SSH Hardening Configuration
# Generated by ssh-hardening setup script

# Disable root login
PermitRootLogin no

# Disable password authentication
PasswordAuthentication no

# Disable empty passwords
PermitEmptyPasswords no

# Limit authentication attempts
MaxAuthTries 3

# Allow only specific users
AllowUsers $SSH_USER

# Use only SSH protocol 2 (should be default)
Protocol 2

# Disable X11 forwarding
X11Forwarding no

# Set login grace time (60 seconds)
LoginGraceTime 60

# Disable host-based authentication
HostbasedAuthentication no

# Disable challenge-response authentication
ChallengeResponseAuthentication no

# Set client alive interval (5 minutes)
ClientAliveInterval 300
ClientAliveCountMax 2

# Enable public key authentication
PubkeyAuthentication yes

# Use PAM
UsePAM yes
EOF

echo "SSH hardening configuration applied to /etc/ssh/sshd_config.d/99-hardening.conf"

# Test SSH configuration
echo ""
echo "[3/3] Testing SSH configuration..."
if sshd -t; then
    echo "✓ SSH configuration is valid"
else
    echo "✗ SSH configuration has errors!"
    echo "Restoring backup..."
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    echo "Backup restored. Please fix errors manually."
    exit 1
fi

# Prompt for restart
echo ""
echo "========================================="
echo "  Configuration Ready"
echo "========================================="
echo ""
echo "BEFORE restarting SSH:"
echo "  1. Keep this SSH session open"
echo "  2. Open a NEW terminal window"
echo "  3. Test SSH login: ssh $SSH_USER@your-server-ip"
echo "  4. Verify you can login successfully"
echo "  5. Test sudo access: sudo whoami"
echo ""
echo "If the test is successful, come back here and restart SSH."
echo ""
read -p "Restart SSH service now? (yes/no): " RESTART

if [ "$RESTART" == "yes" ]; then
    systemctl restart sshd
    echo ""
    echo "✓ SSH service restarted"
    echo ""
    echo "Verify the service is running:"
    systemctl status sshd --no-pager
    echo ""
    echo "Test your connection in a NEW terminal before closing this one!"
else
    echo ""
    echo "SSH service NOT restarted."
    echo "To apply changes, run: sudo systemctl restart sshd"
fi

echo ""
echo "========================================="
echo "  Hardening Complete"
echo "========================================="
echo ""
echo "Configuration backup: $BACKUP_FILE"
echo "New configuration: /etc/ssh/sshd_config.d/99-hardening.conf"
echo ""
echo "Next steps:"
echo "  1. Set up firewall (see firewall-configuration skill)"
echo "  2. Install fail2ban (see fail2ban-setup skill)"
echo "  3. Monitor auth logs: sudo tail -f /var/log/auth.log"
echo ""
