#!/bin/bash

# Google Sheets OAuth2 配置指南

echo "============================================================"
echo "🔧 Google Sheets OAuth2 重定向 URI 配置指南"
echo "============================================================"
echo ""
echo "❌ 错误: redirect_uri_mismatch"
echo ""
echo "这是因为你的 OAuth2 客户端配置中没有添加对应的重定向 URI"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 解决步骤:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  打开 Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials"
echo ""
echo "2️⃣  找到 OAuth 2.0 客户端 ID:"
echo "   994295017900-j3hrfe9f53fil0fe1ek7lbd1ao1df5es.apps.googleusercontent.com"
echo ""
echo "3️⃣  点击 '编辑' (或点击铅笔图标)"
echo ""
echo "4️⃣  在 '已授权的重定向 URI' 部分，点击 '添加 URI'"
echo ""
echo "5️⃣  添加以下 URI（任选其一或全部）:"
echo ""
echo "   推荐（最简单）:"
echo "   urn:ietf:wg:oauth:2.0:oob"
echo ""
echo "   或者（本地回调）:"
echo "   http://localhost:8081"
echo "   http://localhost:8082"
echo ""
echo "6️⃣  点击 '保存'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏳ 等待几分钟后，重新运行授权脚本:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   node scripts/auth-oob.js"
echo ""
echo "============================================================"
echo ""
echo "💡 提示:"
echo "   - 如果添加了 'urn:ietf:wg:oauth:2.0:oob'，授权码会直接显示在浏览器中"
echo "   - 如果添加了 'http://localhost:xxxx'，需要本地服务器监听回调"
echo "   - 修改后可能需要等待 1-2 分钟才能生效"
echo ""
