// Generated by dts-bundle-generator v9.5.1

import { NWCAuthorizationUrlOptions, NostrWebLNProvider } from '@getalby/sdk';
import LNC from '@lightninglabs/lnc-web';
import { GetBalanceResponse, GetInfoResponse, KeysendArgs, LookupInvoiceArgs, LookupInvoiceResponse, MakeInvoiceResponse, RequestInvoiceArgs, SendPaymentResponse, SignMessageResponse, WebLNProvider, WebLNRequestMethod } from '@webbtc/webln-types';
import React$1 from 'react';

declare class ExtensionConnector extends Connector {
	constructor(config: ConnectorConfig);
	init(): Promise<WebLNProvider>;
}
declare class LnbitsConnector extends Connector {
	constructor(config: ConnectorConfig);
	init(): Promise<WebLNProvider>;
}
declare class LnbitsWebLNProvider implements WebLNProvider {
	private _instanceUrl;
	private _adminKey;
	constructor(lnbitsUrl: string, lnbitsAdminKey: string);
	enable(): Promise<void>;
	getInfo(): Promise<GetInfoResponse>;
	makeInvoice(args: string | number | RequestInvoiceArgs): Promise<MakeInvoiceResponse>;
	sendPayment(paymentRequest: string): Promise<SendPaymentResponse>;
	getBalance(): Promise<GetBalanceResponse>;
	keysend(_args: KeysendArgs): Promise<SendPaymentResponse>;
	lnurl(_lnurl: string): Promise<{
		status: "OK";
	} | {
		status: "ERROR";
		reason: string;
	}>;
	lookupInvoice(_args: LookupInvoiceArgs): Promise<LookupInvoiceResponse>;
	request: ((method: WebLNRequestMethod, args?: unknown) => Promise<unknown>) | undefined;
	signMessage(_message: string): Promise<SignMessageResponse>;
	verifyMessage(_signature: string, _message: string): Promise<void>;
	requestLnbits<T>(method: string, path: string, args?: Record<string, unknown>): Promise<T>;
}
declare class NWCConnector extends Connector {
	constructor(config: ConnectorConfig);
	init(): Promise<WebLNProvider>;
}
declare const connectors: {
	"extension.generic": typeof ExtensionConnector;
	"nwc.alby": typeof NWCConnector;
	"nwc.albyhub": typeof NWCConnector;
	"nwc.generic": typeof NWCConnector;
	"nwc.lnfi": typeof NWCConnector;
	"nwc.coinos": typeof NWCConnector;
	"nwc.flash": typeof NWCConnector;
	"nwc.primal": typeof NWCConnector;
	"nwc.cashume": typeof NWCConnector;
	"nwc.lnbits": typeof NWCConnector;
	"nwc.rizful": typeof NWCConnector;
	lnbits: typeof LnbitsConnector;
	lnc: typeof LNCConnector;
};
export declare type ConnectorType = keyof typeof connectors;
export declare type ConnectorConfig = {
	connectorName: string;
	connectorType: ConnectorType;
	nwcUrl?: string;
	lnbitsInstanceUrl?: string;
	lnbitsAdminKey?: string;
};
declare abstract class Connector {
	protected _config: ConnectorConfig;
	constructor(config: ConnectorConfig);
	abstract init(): Promise<WebLNProvider>;
	unload(): Promise<void>;
}
declare class LNCConnector extends Connector {
	constructor(config: ConnectorConfig);
	init(): Promise<WebLNProvider>;
	unload(): Promise<void>;
}
declare class LNCWebLNProvider implements WebLNProvider {
	lnc: LNC;
	constructor(lnc: LNC);
	enable(): Promise<void>;
	getInfo(): Promise<GetInfoResponse>;
	makeInvoice(_args: string | number | RequestInvoiceArgs): Promise<MakeInvoiceResponse>;
	sendPayment(paymentRequest: string): Promise<SendPaymentResponse>;
	getBalance(): Promise<GetBalanceResponse>;
	keysend(_args: KeysendArgs): Promise<SendPaymentResponse>;
	lnurl(_lnurl: string): Promise<{
		status: "OK";
	} | {
		status: "ERROR";
		reason: string;
	}>;
	lookupInvoice(_args: LookupInvoiceArgs): Promise<LookupInvoiceResponse>;
	request: ((method: WebLNRequestMethod, args?: unknown) => Promise<unknown>) | undefined;
	signMessage(_message: string): Promise<SignMessageResponse>;
	verifyMessage(_signature: string, _message: string): Promise<void>;
}
export declare type ConnectorFilter = "nwc";
export declare type PaymentMethods = "all" | "internal" | "external";
export declare type WebLNProviderConfig = {
	nwc?: {
		authorizationUrlOptions: NWCAuthorizationUrlOptions;
	};
};
export declare type BitcoinConnectConfig = {
	/**
	 * Name of the application that the user is interacting with.
	 *   May be passed to the connector the user chooses to connect with (e.g. NWC)
	 */
	appName?: string;
	/**
	 * Icon of the application that the user is interacting with.
	 *   May be passed to the connector the user chooses to connect with (e.g. NWC)
	 */
	appIcon?: string;
	/**
	 * Limit which connectors are shown in the connect flow
	 */
	filters?: ConnectorFilter[];
	/**
	 * Set to false to not request or show the user's wallet balance
	 */
	showBalance?: boolean;
	/**
	 * Automatically connect to a user's NWC wallet when the page loads
	 * NWC connection URL is passed as a hash parameter (URL encoded)
	 * Example: https://myapp.com/#/?nwc=nostr%2Bwalletconnect%3A%2F%2F...
	 * @default true
	 */
	autoConnect?: boolean;
	/**
	 * Save connection configuration to local storage for persistence
	 * Set to false for apps that only need to initialize connection and get NWC secret
	 * @default true
	 */
	persistConnection?: boolean;
	/**
	 * Customize individual providers (NWC, LNC, LNbits etc)
	 */
	providerConfig?: WebLNProviderConfig;
};
export declare type LaunchPaymentModalArgs = {
	/**
	 * Launch a payment flow to pay a BOLT11 invoice
	 */
	invoice: string;
	/**
	 * Supported payment methods in payment flow
	 */
	paymentMethods?: PaymentMethods;
	/**
	 * Called when a payment is made (either with WebLN or externally)
	 * @param response response of the WebLN send payment call
	 */
	onPaid?: (response: SendPaymentResponse) => void;
	/**
	 * Called when modal is closed without completing the payment
	 */
	onCancelled?: () => void;
};
/**
 * Subscribe to onConnected events which will fire when a wallet is connected (either
 * the user connects to a new wallet or when Bitcoin Connect boots and connects to a previously-connected wallet).
 *
 * If a provider is already available when the subscription is created, the callback will be immediately fired.
 * @param callback includes the webln provider that was (or is already) connected
 * @returns unsubscribe function
 */
export declare function onConnected(callback: (provider: WebLNProvider) => void): () => void;
/**
 * Listen to onConnecting events which will fire when a user is connecting to their wallet
 * Subscribe to onConnecting events which will fire when a user is connecting to their wallet
 *
 * If a provider is already being connected to when the subscription is created, the callback will be immediately fired.
 * @param callback
 * @returns unsubscribe function
 */
export declare function onConnecting(callback: () => void): () => void;
/**
 * Listen to onDisconnected events which will fire when a user disconnects from their wallet
 * @param callback
 * @returns unsubscribe function
 */
export declare function onDisconnected(callback: () => void): () => void;
/**
 * Listen to onModalOpened events which will fire when a Bitcoin Connect modal is opened
 * @param callback
 * @returns unsubscribe function
 */
export declare function onModalOpened(callback: () => void): () => void;
/**
 * Listen to onModalOpened events which will fire when a Bitcoin Connect modal is closed
 * @param callback
 * @returns unsubscribe function
 */
export declare function onModalClosed(callback: () => void): () => void;
/**
 * If a WebLN provider already exists, returns the current WebLN provider. Otherwise
 *   will launch the modal to allow the user to connect to a wallet,
 *   and then enable the WebLN provider for that wallet.
 * @returns an enabled WebLN provider.
 * @throws Error if user cancels flow (by closing the modal)
 */
export declare function requestProvider(): Promise<WebLNProvider>;
/**
 * @returns true if user is connected to a wallet and WebLN is enabled
 * @deprecated will be removed in v4.
 */
export declare function isConnected(): boolean;
/**
 * Configures Bitcoin Connect
 * @param config
 */
export declare function init(config?: BitcoinConnectConfig): void;
/**
 * Refresh the balance of the connected wallet
 */
export declare function refreshBalance(): void;
/**
 * Programmatically launch the Bitcoin Connect modal
 */
export declare function launchModal(): void;
/**
 * Programmatically launch the Bitcoin Connect modal to receive a payment
 * @param args configure the payment modal
 *
 * @returns an object allowing you to mark the payment as made (for external payments)
 */
export declare function launchPaymentModal({ invoice, paymentMethods, onPaid, onCancelled, }: LaunchPaymentModalArgs): {
	setPaid: (sendPaymentResponse: SendPaymentResponse) => void;
};
/**
 * Programmatically close the modal
 */
export declare function closeModal(): void;
/**
 * Programmatically connect to a user's wallet
 */
export declare function connect(config: ConnectorConfig): void;
/**
 * Programmatically connect to a user's NWC wallet
 */
export declare function connectNWC(nwcUrl: string): void;
/**
 * Programmatically disconnect from a user's wallet and remove saved configuration
 */
export declare function disconnect(): void;
/**
 * @returns the configuration of the current connector (if connected)
 */
export declare function getConnectorConfig(): ConnectorConfig | undefined;
export declare const WebLNProviders: {
	NostrWebLNProvider: typeof NostrWebLNProvider;
	LNCWebLNProvider: typeof LNCWebLNProvider;
	LnbitsWebLNProvider: typeof LnbitsWebLNProvider;
};
export type ComponentProps = {
	onConnected?(provider: WebLNProvider): void;
	onConnecting?(): void;
	onDisconnected?(): void;
	onModalOpened?(): void;
	onModalClosed?(): void;
};
export type ButtonProps = ComponentProps & {};
export declare const Button: React$1.FC<ButtonProps>;
export type PayButtonProps = ComponentProps & {
	/**
	 * Bolt 11 invoice to pay
	 */
	invoice?: string;
	/**
	 * Supported payment methods in payment flow
	 */
	paymentMethods?: PaymentMethods;
	/**
	 * @param response response of the WebLN send payment call
	 */
	onPaid?: (response: SendPaymentResponse) => void;
	/**
	 * Mark that an external payment was made
	 */
	payment?: SendPaymentResponse;
	/**
	 * Listen to when the pay button is clicked.
	 * This is a good time to fetch an invoice to pay.
	 */
	onClick?: () => void;
};
export declare const PayButton: React$1.FC<PayButtonProps>;
export type ConnectProps = ComponentProps & {};
export declare const Connect: React$1.FC<ConnectProps>;
export type PaymentProps = ComponentProps & {
	/**
	 * Bolt 11 invoice to pay
	 */
	invoice: string;
	/**
	 * Supported payment methods in payment flow
	 */
	paymentMethods?: PaymentMethods;
	/**
	 * @param response response of the WebLN send payment call
	 */
	onPaid?: (response: SendPaymentResponse) => void;
	/**
	 * Mark that an external payment was made
	 */
	payment?: SendPaymentResponse;
};
export declare const Payment: React$1.FC<PaymentProps>;

export {};
