-- ============================================================================
-- Migration 0003: Votes and System Communities
-- Adds upvote/downvote functionality and system community support
-- ============================================================================
-- 
-- NOTE: This migration has been consolidated into 0001_initial_schema.sql
-- All columns and tables below already exist in the initial schema:
-- - communities.is_system  
-- - posts.upvote_count, posts.downvote_count, posts.vote_score
-- - post_votes table with indexes
-- - idx_posts_vote_score index
--
-- This file is kept as a no-op to maintain migration history consistency.
-- ============================================================================
